name: Build and Publish Docker image

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    env: # 在整个 job 中设置环境变量
      DOCKER_USERNAME: sudowanderer

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.DOCKER_USERNAME }}/binance-dca-bot

      - name: Debug metadata
        run: |
          echo "Username: ${{ env.DOCKER_USERNAME }}"
          echo "SHA: $GITHUB_SHA"
          echo "Version: ${{ steps.meta.outputs.version }}"

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ env.DOCKER_USERNAME }}/binance-dca-bot:latest
            ${{ env.DOCKER_USERNAME }}/binance-dca-bot:${{ github.sha}}
            ${{ env.DOCKER_USERNAME }}/binance-dca-bot:${{ steps.meta.outputs.version }}